# Generated by Django 3.1.4 on 2020-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='state',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
